<?php

class builderController extends controller {

    public function __construct() {
        parent::__construct();
    }

    public function indexAction() {
        $builderModel = $this->loadModel('builder');
        $allSchemas = array_values(array_diff(scandir('app/dbschemas/'), ['.', '..', 'logs.sql', 'user.sql', 'menu.sql']));
        $allTables = array_values(array_diff($builderModel->db->getTables(), ['logs', 'user', 'menu']));
        $type = (isset($_POST['type']) && $_POST['type'] != "") ? $_POST['type'] : "";
        $status_desc = "";
        $table_name = "";
        
        if (isset($_POST['action']) && $_POST['action'] == "build" && $type) {
            if ($type == "create") {
                $table_name = (isset($_POST['create'])) ? $_POST['create'] : null;
                $status_desc .= "Table $table_name created<br>";
            } else {
                if ($type == "table") {
                    $table_name = (isset($_POST['tables'])) ? $_POST['tables'] : null;
                    $builderModel->db->createSqlDump($table_name);
                    $status_desc .= "Schema $table_name created<br>";
                } else if ($type == "schema") {
                    $table_name = (isset($_POST['schemas'])) ? $_POST['schemas'] : null;
                    $table_name = str_replace('.sql', '', $table_name);
                    $builderModel->db->createTable($table_name);
                    $status_desc .= "Table $table_name created<br>";
                } else {
                    $status_desc .= "No start option was chosen<br>";
                    die;
                }
            }
            $columns = $builderModel->db->getTableColumns($table_name);
            if (isset($_POST['wish-model']) && $_POST['wish-model'] == "1") {
                $this->createModel($table_name, $columns, $type);
                $status_desc .= "Class " . $table_name . "Model created<br>";
            }
            if (isset($_POST['wish-controller']) && $_POST['wish-controller'] == "1") {
                $this->createController($table_name, $columns, $type);
                $status_desc .= "Class " . $table_name . "Controller created<br>";
            }
            if (isset($_POST['wish-view-index']) && $_POST['wish-view-index'] == "1") {
                $this->createViewIndex($table_name);
                $builderModel->addToMenu($table_name, 'index', 1);
                $status_desc .= "View " . $table_name . "Update created and added in menu<br>";
            }
            if (isset($_POST['wish-view-update']) && $_POST['wish-view-update'] == "1") {
                $this->createViewUpdate($table_name);
                $builderModel->addToMenu($table_name, 'update', 2);
                $status_desc .= "View " . $table_name . "Update created and added in menu<br>";
            }
        }
        $this->view->assign('tables', $allTables);
        $this->view->assign('schemas', $allSchemas);
        $this->view->assign('status', $status_desc);
        $this->view->render('builder/index');
    }
    
    private function createViewUpdate($table) {
        $structure = 'app/content/views/' . TEMPLATE . '/' . $table . "/";
        $filestring = file_get_contents('app/views/' . TEMPLATE . '/builder/templates/update.php');
        $filestring = str_replace('[f[tablename]f]', $table, $filestring);
//        echo "<pre>";
//        var_dump($filestring);
        $filestring = str_replace('[f[tablename_capital]f]', ucfirst($table), $filestring);
//        var_dump($filestring);
        //die;
        if (!is_dir($structure)) {
            if (!mkdir($structure, 0777, true)) {
                echo "Failed to create folder...";
            }
        }
        file_put_contents($structure . 'update.php', $filestring);
    }
    
    private function createViewIndex($table) {
        $fileString = "<h3>This is autogenerated text.</h3>";
        $structure = 'app/content/views/' . TEMPLATE . '/' . $table . "/";
        if(!mkdir($structure, 0777, true)) {
            echo "Failed to create folder...";
        } else {
            file_put_contents("app/content/views/" . TEMPLATE . "/" . $table . "/index.php", $fileString);
        }
    }
    
    private function createModel($table, $columns=[], $type) {
        $fileString = "<?php";
        $fileString .=  "\n\n";
        $fileString .= "class " . $table . "Model extends model {";
        $fileString .=  "\n\n";
        foreach($columns as $singleColumn) {
            $fileString .= "\tpublic $" . $singleColumn . ";\n";
        }
        $fileString .=  "\n\n";
        $fileString .= "\tpublic function __construct() { ";
        $fileString .= "\n";
        $fileString .= "\t\tparent::__construct();\n";
        $fileString .= "\t}";
        $fileString .= "\n\n";
        if ($type != 'create') {
            foreach($columns as $singleColumn) {
                $fileString .= "\tpublic function get" . ucfirst($singleColumn) . "() {\n";
                $fileString .= "\t\treturn $" . "this->" . $singleColumn . ";\n";
                $fileString .= "\t}\n\n";
                $fileString .= "\tpublic function set" . ucfirst($singleColumn) . "($" . $singleColumn . ") {\n";
                $fileString .= "\t\t$" . "this->" . $singleColumn . " = $" . $singleColumn . ";\n";
                $fileString .= "\t\treturn $". "this;\n";
                $fileString .= "\t}\n\n";
                $fileString .= "\tpublic function findOneBy" . ucfirst($singleColumn) . "($" . "value) {\n";
                $fileString .= "\t\t$" . "result = $" . "this->db->findOneByParam('" . $singleColumn . "', $" . "value, '" . $table . "');\n";
                $fileString .= "\t\t$" . "this->fill" . ucfirst($table) . "($" . "result);\n";
                $fileString .= "\t\treturn $" . "this;\n";
                $fileString .= "\t}\n\n";
            }
            $fileString .= "\tpublic function findAll() {\n";
            $fileString .= "\t\treturn $" . "this->db->findAll('" . $table . "');\n";
            $fileString .= "\t}";
            $fileString .= "\n\n";
            $fileString .= "\tpublic function flush($" . "sqlDump=0) {\n";
            $fileString .= "\t\t$" . "this->db->flush($" . "this, '" . $table . "', $" . "sqlDump);\n";
            $fileString .= "\t}";
            $fileString .= "\n\n";
            $fileString .= "\tpublic function remove() {\n";
            $fileString .= "\t\t$" . "this->db->delete($" . "this, '" . $table . "');\n";
            $fileString .= "\t}";
            $fileString .= "\n\n";
            $fileString .= "\tpublic function fill" . ucfirst($table) . "($" . "data) {\n";
            $fileString .= "\t\t$" . "columns = $" . "this->db->getTableColumns('" . $table . "');\n";
            $fileString .= "\t\tforeach($" . "data as $" . "key => $" . "value) {\n";
            $fileString .= "\t\t\t$" . "this->$" . "key = $" . "value;\n";
            $fileString .= "\t\t}\n";
            $fileString .= "\t\treturn $" . "this;\n";
            $fileString .= "\t}";
        }
        $fileString .= "\n}";
        file_put_contents("app/content/models/" . $table . "Model.php", $fileString);
    }
    
    private function createController($table, $columns=[], $type) {
        $fileString = "<?php";
        $fileString .=  "\n\n";
        $fileString .= "class " . $table . "Controller extends controller {";
        $fileString .=  "\n\n";
        $fileString .= "\tpublic function __construct() { ";
        $fileString .= "\n";
        $fileString .= "\t\tparent::__construct();";
        $fileString .= "\n\t}";
        $fileString .= "\n\n\t";
        $fileString .= 'public function indexAction($id=0) {';
        $fileString .= "\n\t\t";
        $fileString .= '$this->view->render("' . $table . '/index");';
        $fileString .= "\n\t";
        $fileString .= '}';
        if ($type != 'create') {
            $fileString .= "\n\n\t";
            $fileString .= 'public function updateAction($id=0) {';
            $fileString .= "\n";
            $fileString .= "\t\t";
            $fileString .= "$" . "this->tools->checkPageRights(4);";
            $fileString .= "\n";
            $fileString .= "\t\t";
            $fileString .= '$' . $table . 'Model = $this->loadModel("' . $table . '");';
            $fileString .= "\n";
            $fileString .= "\t\t";
            $fileString .= 'if($id != 0) {';
            $fileString .= "\n";
            $fileString .= "\t\t\t";
            $fileString .= '$' . $table . 'Model->findOneById($id);';
            $fileString .= "\n";
            $fileString .= "\t\t";
            $fileString .= "}";
            $fileString .= "\n";
            $fileString .= "\t\t";
            $fileString .= 'if(isset($_POST["action"]) && $_POST["action"] == "handle' . $table . '") {';
            foreach($columns as $singleColumn) {
                if ($singleColumn != 'id') {
                    $fileString .= "\n\t\t\t";
                    $fileString .= '$' . $table . 'Model->set' . ucfirst($singleColumn) . '($this->tools->sanitizePost($_POST["' . $table . '-' . $singleColumn . '"]));';
                }
            }
            $fileString .= "\n\t\t\t";
            $fileString .= '$' . $table . 'Model->flush();';
            $fileString .= "\n\t\t\t";
            $fileString .= '$action = ($id != 0) ? "' . ucfirst($table) . ' element with id: $id updated successfully." : "' . $table . ' successfully added.";';
            $fileString .= "\n\t\t\t";
            $fileString .= '$this->tools->notification("' . $table . ' element dodan/urejen.", "primary");';
            $fileString .= "\n\t\t\t";
            $fileString .= '$this->tools->log("' . $table . '", $action);';
            $fileString .= "\n\t\t";
            $fileString .= "}";
            $fileString .= "\n\t\t";
            $fileString .= "$" . "columns = $" . "testModel->db->getTableColumns('" . $table . "');";
            $fileString .= "\n\t\t";
            $fileString .= '$allItems = $' . $table . 'Model->findAll();';
            $fileString .= "\n\t\t";
            $fileString .= '$this->view->assign("items", $allItems);';
            $fileString .= "\n\t\t";
            $fileString .= '$this->view->assign("selected' . ucfirst($table) . '", $' . $table . 'Model);';
            $fileString .= "\n\t\t";
            $fileString .= '$this->view->assign("columns", $columns);';
            $fileString .= "\n\t\t";
            $fileString .= '$this->view->render("' . $table . '/update");';
            $fileString .= "\n\t";
            $fileString .= '}';
            $fileString .= "\n\n\t";
            $fileString .= 'public function removeAction($id) {';
            $fileString .= "\n\t\t";
            $fileString .= 'if ($id) {';
            $fileString .= "\n\t\t\t";
            $fileString .= '$' . $table . 'Model = $this->loadModel("' . $table . '");';
            $fileString .= "\n\t\t\t";
            $fileString .= '$' . $table . 'Model->findOneById($id);';
            $fileString .= "\n\t\t\t";
            $fileString .= '$' . $table . 'Model->remove();';
            $fileString .= "\n\t\t\t";
            $fileString .= '$this->tools->log("' . $table . '", "' . ucfirst($table) . ' element with id: $id removed.");';
            $fileString .= "\n\t\t\t";
            $fileString .= '$this->tools->redirect(URL . "' . $table . '/update");';
            $fileString .= "\n\t\t";
            $fileString .= '} else {';
            $fileString .= "\n\t\t\t";
            $fileString .= 'echo "No ' . $table . ' element id selected!";';
            $fileString .= "\n\t\t";
            $fileString .= '}';
            $fileString .= "\n\t";
            $fileString .= '}';
        }
        $fileString .= "\n";
        $fileString .= '}';
        file_put_contents("app/content/controllers/" . $table . "Controller.php", $fileString);
    }
}
